[Distribution]
Distribution=fedora

[Output]
Format=disk

[Content]
Bootable=yes
Bootloader=systemd-boot
RootPassword=hashed: # No password
Packages=
	kernel
	systemd
	systemd-udev
	systemd-boot
	systemd-networkd
	systemd-resolved
	systemd-pam
	dbus
	bash
	coreutils
	util-linux
	fuse3
	jq
	rpm
